"""initial schema

Revision ID: a46a6eaa3652
Revises: 
Create Date: 2026-05-23 21:37:20.556508
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a46a6eaa3652'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('province', sa.Enum('ON', 'QC', 'BC', 'AB', 'MB', 'SK', 'NS', 'NB', 'NL', 'PE', name='province', native_enum=False), nullable=False),
    sa.Column('language', sa.Enum('EN', 'FR', name='language', native_enum=False), nullable=False),
    sa.Column('esa_license_number', sa.String(length=60), nullable=True),
    sa.Column('rbq_license_number', sa.String(length=60), nullable=True),
    sa.Column('cmeq_membership_number', sa.String(length=60), nullable=True),
    sa.Column('blended_labor_rate_cad', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('apprentice_labor_rate_cad', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('default_material_markup_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('default_labor_markup_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('minimum_callout_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('minimum_margin_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color_hex', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('province', sa.Enum('ON', 'QC', 'BC', 'AB', 'MB', 'SK', 'NS', 'NB', 'NL', 'PE', name='province', native_enum=False), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('quote_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'APPROVED', 'DECLINED', 'EXPIRED', name='quotestatus', native_enum=False, length=12), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_site_address', sa.String(length=400), nullable=True),
    sa.Column('province', sa.Enum('ON', 'QC', 'BC', 'AB', 'MB', 'SK', 'NS', 'NB', 'NL', 'PE', name='province', native_enum=False), nullable=False),
    sa.Column('code_edition', sa.String(length=120), nullable=False),
    sa.Column('permit_expected_date', sa.Date(), nullable=True),
    sa.Column('subtotal_materials_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_labor_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_permits_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_other_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_gst_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pst_qst_hst_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('customer_facing_scope_en', sa.Text(), nullable=True),
    sa.Column('customer_facing_scope_fr', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=False),
    sa.Column('audit_passed', sa.Boolean(), nullable=False),
    sa.Column('audit_overrides', sa.JSON(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('customer_language', sa.Enum('EN', 'FR', name='language', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quote_number', name='uq_quote_number_per_user')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_quote_number'), ['quote_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_user_id'), ['user_id'], unique=False)

    op.create_table('estimate_audit_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'CRITICAL', name='flagseverity', native_enum=False, length=10), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('message_fr', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimate_audit_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimate_audit_flags_quote_id'), ['quote_id'], unique=False)

    op.create_table('llm_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cad', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_sessions_quote_id'), ['quote_id'], unique=False)

    op.create_table('quote_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ASSEMBLY', 'CUSTOM', 'PERMIT', name='linesource', native_enum=False, length=10), nullable=False),
    sa.Column('assembly_id', sa.String(length=80), nullable=True),
    sa.Column('description_en', sa.String(length=400), nullable=False),
    sa.Column('description_fr', sa.String(length=400), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('materials_cost_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('labor_cost_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('code_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_line_items_quote_id'), ['quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_line_items_quote_id'))

    op.drop_table('quote_line_items')
    with op.batch_alter_table('llm_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_sessions_quote_id'))

    op.drop_table('llm_sessions')
    with op.batch_alter_table('estimate_audit_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimate_audit_flags_quote_id'))

    op.drop_table('estimate_audit_flags')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_user_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_quote_number'))
        batch_op.drop_index(batch_op.f('ix_quotes_customer_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))

    op.drop_table('customers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
