/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness + DB connectivity check (§18).
         */
        get: operations["healthz_api_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logos/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logo
         * @description Serve a contractor logo from the volume. Public (logos appear on quotes).
         */
        get: operations["get_logo_api_logos__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assemblies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assemblies
         * @description Reference list of assemblies available to the engine.
         *
         *     Includes draft assemblies (with a flag) since none are electrician-reviewed
         *     yet (§8); the LLM index — separate — only exposes reviewed ones.
         */
        get: operations["list_assemblies_api_assemblies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estimate/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_estimate_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Request */
        post: operations["password_reset_request_api_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Confirm */
        post: operations["password_reset_confirm_api_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/me/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Logo */
        post: operations["upload_logo_api_me_logo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        /** Delete Customer */
        delete: operations["delete_customer_api_customers__customer_id__delete"];
        options?: never;
        head?: never;
        /** Update Customer */
        patch: operations["update_customer_api_customers__customer_id__patch"];
        trace?: never;
    };
    "/api/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quotes */
        get: operations["list_quotes_api_quotes_get"];
        put?: never;
        /** Create Quote */
        post: operations["create_quote_api_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_quotes__quote_id__get"];
        put?: never;
        post?: never;
        /** Delete Quote */
        delete: operations["delete_quote_api_quotes__quote_id__delete"];
        options?: never;
        head?: never;
        /** Update Quote */
        patch: operations["update_quote_api_quotes__quote_id__patch"];
        trace?: never;
    };
    "/api/quotes/{quote_id}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_api_quotes__quote_id__recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audit */
        post: operations["audit_api_quotes__quote_id__audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/override-flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override Flag */
        post: operations["override_flag_api_quotes__quote_id__override_flag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize */
        post: operations["finalize_api_quotes__quote_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send */
        post: operations["send_api_quotes__quote_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/mark-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Status */
        post: operations["mark_status_api_quotes__quote_id__mark_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_quotes__quote_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/answer-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Question */
        post: operations["answer_question_api_quotes__quote_id__answer_question_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pdf */
        get: operations["pdf_api_quotes__quote_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerQuestionRequest */
        AnswerQuestionRequest: {
            /** Answer */
            answer: string;
        };
        /** AssemblyRequestIn */
        AssemblyRequestIn: {
            /** Assembly Id */
            assembly_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number | string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** AuditFlagOut */
        AuditFlagOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            severity: components["schemas"]["FlagSeverity"];
            /** Code */
            code: string;
            /** Message En */
            message_en: string;
            /** Message Fr */
            message_fr: string;
            /** Suggested Action */
            suggested_action: string;
            /** Overridden */
            overridden: boolean;
            /** Overridden At */
            overridden_at: string | null;
        };
        /** Body_upload_logo_api_me_logo_post */
        Body_upload_logo_api_me_logo_post: {
            /** File */
            file: string;
        };
        /** ContractorRatesIn */
        ContractorRatesIn: {
            /** Blended Labor Rate Cad */
            blended_labor_rate_cad: number | string;
            /**
             * Apprentice Labor Rate Cad
             * @default 0
             */
            apprentice_labor_rate_cad: number | string;
            /**
             * Labor Cost Rate Cad
             * @default 0
             */
            labor_cost_rate_cad: number | string;
            /**
             * Default Material Markup Pct
             * @default 35
             */
            default_material_markup_pct: number | string;
            /**
             * Default Labor Markup Pct
             * @default 0
             */
            default_labor_markup_pct: number | string;
            /**
             * Minimum Callout Hours
             * @default 1
             */
            minimum_callout_hours: number | string;
            /**
             * Minimum Margin Pct
             * @default 20
             */
            minimum_margin_pct: number | string;
        };
        /** CustomLineItemIn */
        CustomLineItemIn: {
            /** Description En */
            description_en: string;
            /** Description Fr */
            description_fr: string;
            /** Amount Cad */
            amount_cad: number | string;
            /**
             * Source
             * @default custom
             */
            source: string;
            /**
             * Labor Hours
             * @default 0
             */
            labor_hours: number | string;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Name */
            name: string;
            /** Company */
            company?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2?: string | null;
            /** City */
            city: string;
            province: components["schemas"]["Province"];
            /** Postal Code */
            postal_code: string;
            /** Notes */
            notes?: string | null;
        };
        /** CustomerOut */
        CustomerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Company */
            company: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2: string | null;
            /** City */
            city: string;
            province: components["schemas"]["Province"];
            /** Postal Code */
            postal_code: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CustomerUpdate */
        CustomerUpdate: {
            /** Name */
            name?: string | null;
            /** Company */
            company?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address Line1 */
            address_line1?: string | null;
            /** Address Line2 */
            address_line2?: string | null;
            /** City */
            city?: string | null;
            province?: components["schemas"]["Province"] | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** EstimatePreviewRequest */
        EstimatePreviewRequest: {
            contractor: components["schemas"]["ContractorRatesIn"];
            province: components["schemas"]["Province"];
            /** Code Edition */
            code_edition: string;
            /** Assemblies */
            assemblies: components["schemas"]["AssemblyRequestIn"][];
            /** Additional Line Items */
            additional_line_items?: components["schemas"]["CustomLineItemIn"][];
            /** Material Markup Pct */
            material_markup_pct?: number | string | null;
            /** Labor Markup Pct */
            labor_markup_pct?: number | string | null;
            /**
             * Job Description
             * @default
             */
            job_description: string;
            /**
             * Customer Facing Scope
             * @default
             */
            customer_facing_scope: string;
            customer_province?: components["schemas"]["Province"] | null;
            /**
             * Customer Language
             * @default en
             */
            customer_language: string;
            /** Permit Date */
            permit_date?: string | null;
        };
        /** EstimatePreviewResponse */
        EstimatePreviewResponse: {
            /** Line Items */
            line_items: components["schemas"]["LineItemOut"][];
            /** Subtotal Materials Cad */
            subtotal_materials_cad: string;
            /** Subtotal Labor Cad */
            subtotal_labor_cad: string;
            /** Subtotal Permits Cad */
            subtotal_permits_cad: string;
            /** Subtotal Other Cad */
            subtotal_other_cad: string;
            tax: components["schemas"]["TaxOut"];
            /** Total Cad */
            total_cad: string;
            /** Gross Margin Pct */
            gross_margin_pct: string;
            /** Code Edition */
            code_edition: string;
            /** Assumptions */
            assumptions: string[];
            /** Audit Flags */
            audit_flags: components["schemas"]["PreviewAuditFlagOut"][];
            /** Audit Passed */
            audit_passed: boolean;
            /** Pdf Blocked */
            pdf_blocked: boolean;
        };
        /**
         * FlagSeverity
         * @enum {string}
         */
        FlagSeverity: "info" | "warn" | "critical";
        /** GenerateRequest */
        GenerateRequest: {
            /** Job Description */
            job_description?: string | null;
        };
        /** GenerationResponse */
        GenerationResponse: {
            /** Status */
            status: string;
            /** Question */
            question?: {
                [key: string]: unknown;
            } | null;
            /**
             * Assistant Text
             * @default
             */
            assistant_text: string;
            /**
             * Error
             * @default
             */
            error: string;
            quote: components["schemas"]["QuoteOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Language
         * @enum {string}
         */
        Language: "en" | "fr";
        /** LineItemOut */
        LineItemOut: {
            /** Line Number */
            line_number: number;
            /** Source */
            source: string;
            /** Assembly Id */
            assembly_id: string | null;
            /** Description En */
            description_en: string;
            /** Description Fr */
            description_fr: string;
            /** Quantity */
            quantity: string;
            /** Materials Cost Cad */
            materials_cost_cad: string;
            /** Labor Hours */
            labor_hours: string;
            /** Labor Cost Cad */
            labor_cost_cad: string;
            /** Line Total Cad */
            line_total_cad: string;
            /** Code Refs */
            code_refs: {
                [key: string]: unknown;
            }[];
        };
        /**
         * LineSource
         * @enum {string}
         */
        LineSource: "assembly" | "custom" | "permit";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarkStatusRequest */
        MarkStatusRequest: {
            status: components["schemas"]["QuoteStatus"];
        };
        /** OverrideFlagRequest */
        OverrideFlagRequest: {
            /**
             * Flag Id
             * Format: uuid
             */
            flag_id: string;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PreviewAuditFlagOut */
        PreviewAuditFlagOut: {
            /** Severity */
            severity: string;
            /** Code */
            code: string;
            /** Message En */
            message_en: string;
            /** Message Fr */
            message_fr: string;
            /** Suggested Action En */
            suggested_action_en: string;
            /** Suggested Action Fr */
            suggested_action_fr: string;
        };
        /**
         * Province
         * @enum {string}
         */
        Province: "ON" | "QC" | "BC" | "AB" | "MB" | "SK" | "NS" | "NB" | "NL" | "PE";
        /** QuoteCreate */
        QuoteCreate: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Job Title */
            job_title: string;
            /**
             * Job Description
             * @default
             */
            job_description: string;
            /** Job Site Address */
            job_site_address?: string | null;
            province?: components["schemas"]["Province"] | null;
            /** Code Edition */
            code_edition?: string | null;
            /** Permit Expected Date */
            permit_expected_date?: string | null;
            customer_language?: components["schemas"]["Language"] | null;
            /** Valid Until */
            valid_until?: string | null;
            /** Line Items */
            line_items?: components["schemas"]["QuoteLineItemIn"][];
        };
        /**
         * QuoteLineItemIn
         * @description A contractor-specified input line. Computed costs are filled by the engine.
         */
        QuoteLineItemIn: {
            /** @default assembly */
            source: components["schemas"]["LineSource"];
            /** Assembly Id */
            assembly_id?: string | null;
            /**
             * Quantity
             * @default 1
             */
            quantity: number | string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Description En */
            description_en?: string | null;
            /** Description Fr */
            description_fr?: string | null;
            /** Amount Cad */
            amount_cad?: number | string | null;
            /**
             * Labor Hours
             * @default 0
             */
            labor_hours: number | string;
        };
        /** QuoteLineItemOut */
        QuoteLineItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Line Number */
            line_number: number;
            source: components["schemas"]["LineSource"];
            /** Assembly Id */
            assembly_id: string | null;
            /** Description En */
            description_en: string;
            /** Description Fr */
            description_fr: string;
            /** Quantity */
            quantity: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Materials Cost Cad */
            materials_cost_cad: string;
            /** Labor Hours */
            labor_hours: string;
            /** Labor Cost Cad */
            labor_cost_cad: string;
            /** Line Total Cad */
            line_total_cad: string;
            /** Code Refs */
            code_refs: unknown[];
        };
        /** QuoteOut */
        QuoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Quote Number */
            quote_number: string;
            status: components["schemas"]["QuoteStatus"];
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string;
            /** Job Site Address */
            job_site_address: string | null;
            province: components["schemas"]["Province"];
            /** Code Edition */
            code_edition: string;
            /** Permit Expected Date */
            permit_expected_date: string | null;
            /** Subtotal Materials Cad */
            subtotal_materials_cad: string;
            /** Subtotal Labor Cad */
            subtotal_labor_cad: string;
            /** Subtotal Permits Cad */
            subtotal_permits_cad: string;
            /** Subtotal Other Cad */
            subtotal_other_cad: string;
            /** Tax Gst Cad */
            tax_gst_cad: string;
            /** Tax Pst Qst Hst Cad */
            tax_pst_qst_hst_cad: string;
            /** Total Cad */
            total_cad: string;
            /** Gross Margin Pct */
            gross_margin_pct: string;
            /** Customer Facing Scope En */
            customer_facing_scope_en: string | null;
            /** Customer Facing Scope Fr */
            customer_facing_scope_fr: string | null;
            /** Internal Notes */
            internal_notes: string;
            /** Audit Passed */
            audit_passed: boolean;
            /** Valid Until */
            valid_until: string | null;
            customer_language: components["schemas"]["Language"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Line Items */
            line_items: components["schemas"]["QuoteLineItemOut"][];
            /** Audit Flags */
            audit_flags: components["schemas"]["AuditFlagOut"][];
            /**
             * Pdf Blocked
             * @default false
             */
            pdf_blocked: boolean;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "draft" | "sent" | "approved" | "declined" | "expired";
        /** QuoteSummary */
        QuoteSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quote Number */
            quote_number: string;
            status: components["schemas"]["QuoteStatus"];
            /** Job Title */
            job_title: string;
            /** Total Cad */
            total_cad: string;
            /** Gross Margin Pct */
            gross_margin_pct: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuoteUpdate */
        QuoteUpdate: {
            /** Job Title */
            job_title?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Job Site Address */
            job_site_address?: string | null;
            /** Code Edition */
            code_edition?: string | null;
            /** Permit Expected Date */
            permit_expected_date?: string | null;
            customer_language?: components["schemas"]["Language"] | null;
            /** Valid Until */
            valid_until?: string | null;
            /** Internal Notes */
            internal_notes?: string | null;
            /** Customer Facing Scope En */
            customer_facing_scope_en?: string | null;
            /** Customer Facing Scope Fr */
            customer_facing_scope_fr?: string | null;
            /** Line Items */
            line_items?: components["schemas"]["QuoteLineItemIn"][] | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Business Name */
            business_name: string;
            province: components["schemas"]["Province"];
            language?: components["schemas"]["Language"] | null;
        };
        /** TaxOut */
        TaxOut: {
            /** Gst Cad */
            gst_cad: string;
            /** Gst Rate */
            gst_rate: string;
            /** Pst Qst Hst Cad */
            pst_qst_hst_cad: string;
            /** Pst Qst Hst Rate */
            pst_qst_hst_rate: string;
            /** Pst Qst Hst Label En */
            pst_qst_hst_label_en: string;
            /** Total Tax Cad */
            total_tax_cad: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Business Name */
            business_name: string;
            province: components["schemas"]["Province"];
            language: components["schemas"]["Language"];
            /** Esa License Number */
            esa_license_number: string | null;
            /** Rbq License Number */
            rbq_license_number: string | null;
            /** Cmeq Membership Number */
            cmeq_membership_number: string | null;
            /** Business Email */
            business_email: string | null;
            /** Business Phone */
            business_phone: string | null;
            /** Business Address Line1 */
            business_address_line1: string | null;
            /** Business Address Line2 */
            business_address_line2: string | null;
            /** Business City */
            business_city: string | null;
            /** Business Postal Code */
            business_postal_code: string | null;
            /** Blended Labor Rate Cad */
            blended_labor_rate_cad: string;
            /** Apprentice Labor Rate Cad */
            apprentice_labor_rate_cad: string;
            /** Labor Cost Rate Cad */
            labor_cost_rate_cad: string;
            /** Default Material Markup Pct */
            default_material_markup_pct: string;
            /** Default Labor Markup Pct */
            default_labor_markup_pct: string;
            /** Minimum Callout Hours */
            minimum_callout_hours: string;
            /** Minimum Margin Pct */
            minimum_margin_pct: string;
            /** Logo Url */
            logo_url: string | null;
            /** Primary Color Hex */
            primary_color_hex: string | null;
        };
        /**
         * UserUpdate
         * @description Partial update of business defaults, branding, and licensing (PATCH /me).
         */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Business Name */
            business_name?: string | null;
            province?: components["schemas"]["Province"] | null;
            language?: components["schemas"]["Language"] | null;
            /** Esa License Number */
            esa_license_number?: string | null;
            /** Rbq License Number */
            rbq_license_number?: string | null;
            /** Cmeq Membership Number */
            cmeq_membership_number?: string | null;
            /** Business Email */
            business_email?: string | null;
            /** Business Phone */
            business_phone?: string | null;
            /** Business Address Line1 */
            business_address_line1?: string | null;
            /** Business Address Line2 */
            business_address_line2?: string | null;
            /** Business City */
            business_city?: string | null;
            /** Business Postal Code */
            business_postal_code?: string | null;
            /** Blended Labor Rate Cad */
            blended_labor_rate_cad?: number | string | null;
            /** Apprentice Labor Rate Cad */
            apprentice_labor_rate_cad?: number | string | null;
            /** Labor Cost Rate Cad */
            labor_cost_rate_cad?: number | string | null;
            /** Default Material Markup Pct */
            default_material_markup_pct?: number | string | null;
            /** Default Labor Markup Pct */
            default_labor_markup_pct?: number | string | null;
            /** Minimum Callout Hours */
            minimum_callout_hours?: number | string | null;
            /** Minimum Margin Pct */
            minimum_margin_pct?: number | string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Primary Color Hex */
            primary_color_hex?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_logo_api_logos__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assemblies_api_assemblies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    preview_api_estimate_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimatePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimatePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_request_api_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_confirm_api_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_logo_api_me_logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_api_me_logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_customers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
        };
    };
    create_customer_api_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_customer_api_customers__customer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_customers__customer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quotes_api_quotes_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["QuoteStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_quote_api_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_quotes__quote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_quote_api_quotes__quote_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quote_api_quotes__quote_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_api_quotes__quote_id__recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_quotes__quote_id__audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_flag_api_quotes__quote_id__override_flag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideFlagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_quotes__quote_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_api_quotes__quote_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_status_api_quotes__quote_id__mark_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_quotes__quote_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_quotes__quote_id__answer_question_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdf_api_quotes__quote_id__pdf_get: {
        parameters: {
            query?: {
                variant?: string;
            };
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
